name: publish-latest-upstream-alpha

on:
  schedule:
    - cron: '13 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: publish-latest-upstream-alpha-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    uses: ./.github/workflows/_publish-upstream-release-core.yml
    with:
      release_channel: sync
      artifact_prefix: spm
